name: deploy-to-gh-pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - run: npm install -g gatsby-cli
    - run: npm install
    - run: gatsby build --prefix-paths && gh-pages -d public -r https://$GH_TOKEN@github.com/iqan/fariqan.git -u "Iqan Shaikh <$EMAIL>"
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        EMAIL: ${{ secrets.EMAIL }}
